name: Alias

default_ecosystem: ethereum

plugins:
  - name: solidity
    version: 0.6.5

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.9.0"
