name: Alias

plugins:
  - name: solidity
  - name: fantom
  - name: polygon

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.9.0"
